<?php

namespace AppBundle\Repository;

/**
 * DataSensorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSensorRepository extends \Doctrine\ORM\EntityRepository
{
}
