app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

app_data_sensor_api:
    resource: "@AppBundle/Controller/DataSensorRESTController.php"
    type:   rest
    prefix:   /api

app_sensor_update_status:
    methods:  GET
    path: /api/sensors/updateStatus/{id}
    defaults: { _controller: "AppBundle:Sensor:updateStatus" }
    options:
        expose: true

#REST
rest :
    type : rest
    resource : "routing_rest.yml"
    prefix : /api